[package]
name = "map-issue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
topojson = "~0.5"
d3_geo_rs = "*"
geo = "~0.25"
geo-types = "~0.7"
geojson = "*"
